return {
  {
    "ThePrimeagen/harpoon",
    keys = {
      {
        "<leader>h",
        desc = "Harpoon",
      },
      {
        "<leader>hh",
        function()
          require("harpoon.ui").toggle_quick_menu()
        end,
        desc = "List harpoons",
      },
      {
        "",
        function()
          require("harpoon.ui").nav_prev()
        end,
      },
      {
        "",
        function()
          require("harpoon.ui").nav_next()
        end,
      },
      {
        "<F22>",
        function()
          require("harpoon.mark").add_file()
        end,
      },
      {
        "<F13>",
        function()
          require("harpoon.ui").nav_file(1)
        end,
      },
      {
        "<F14>",
        function()
          require("harpoon.ui").nav_file(2)
        end,
      },
      {
        "<F15>",
        function()
          require("harpoon.ui").nav_file(3)
        end,
      },
      {
        "<F16>",
        function()
          require("harpoon.ui").nav_file(4)
        end,
      },
      {
        "<F17>",
        function()
          require("harpoon.ui").nav_file(5)
        end,
      },
      {
        "<F18>",
        function()
          require("harpoon.ui").nav_file(6)
        end,
      },
      {
        "<F19>",
        function()
          require("harpoon.ui").nav_file(7)
        end,
      },
      {
        "<F20>",
        function()
          require("harpoon.ui").nav_file(8)
        end,
      },
      {
        "<F21>",
        function()
          require("harpoon.ui").nav_file(9)
        end,
      },
    },
  },
}
